### ISSUE TITLE
The error occurred during testing of boom core

### ISSUE THREAD

**Issue by RafalHan** [riscv-boom/riscv-boom#688]
**Type of issue**: question

Why does my scalaVersion use the default setting 2.13.10, but when testing boom core, it reports the following error, claiming it cannot find the rocketchip_2.13-1.6.0.pom file?

<img width="841" alt="image" src="https://github.com/riscv-boom/riscv-boom/assets/62008997/8bc49104-5296-4b67-b520-b3bc8842eebd">

**Comment by yoyo115956** [comment]
Indeed, I've encountered the same problem today, and feel that the likely reason is that the installer for rocketchip 2.13 is no longer being offered.
See this installer site https://repo1.maven.org/maven2/edu/berkeley/cs/

**Comment by yoyo115956** [comment]
Maybe you can try the method here too, it might work:
https://github.com/ucb-bar/constellation/issues/50

**Comment by yoyo115956** [comment]
The detailed code is as follows: 
git clone https://github.com/chipsalliance/rocket-chip.git
cd rocket-chip
git checkout 4fbd2f238db36b2862319e94c2f96d63bd52c98b
git submodule update --init --recursive
sbt "publishLocal"
sbt "project cde; set publishArtifact := true; publishLocal"
sbt "project rocket-macros; set publishArtifact := true; publishLocal"
sbt "project hardfloat; set publishArtifact := true; publishLocal"

**Comment by SeddonShen** [comment]
> The detailed code is as follows: git clone https://github.com/chipsalliance/rocket-chip.git cd rocket-chip git checkout 4fbd2f238db36b2862319e94c2f96d63bd52c98b git submodule update --init --recursive sbt "publishLocal" sbt "project cde; set publishArtifact := true; publishLocal" sbt "project rocket-macros; set publishArtifact := true; publishLocal" sbt "project hardfloat; set publishArtifact := true; publishLocal"

by the way, what is the sbt version you use, I try to publishLocal but meet new problem:

```log
[info] welcome to sbt 1.3.13 (AdoptOpenJDK Java 1.8.0_292)
[info] loading settings for project rocket-chip-build from plugins.sbt ...
[info] loading project definition from /Users/seddonshen/Coding/ooo_20240628/rocket-chip/project
[info] Updating 
https://repo1.maven.org/maven2/ch/epfl/scala/sbt-scalafix_2.12_1.0/0.10.4/sbt-scalafix-0.10.4.pom
  100.0% [##########] 3.1 KiB (1.3 KiB / s)
[info] Resolved  dependencies
[warn] 
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]          com.typesafe:sbt-mima-plugin:0.6.1 (sbtVersion=1.0, scalaVersion=2.12)
[warn]          com.eed3si9n:sbt-unidoc:0.4.1 (sbtVersion=1.0, scalaVersion=2.12)
[warn]          com.typesafe.sbt:sbt-site:1.3.1 (sbtVersion=1.0, scalaVersion=2.12)
[warn]          com.eed3si9n:sbt-buildinfo:0.10.0 (sbtVersion=1.0, scalaVersion=2.12)
[warn]          com.eed3si9n:sbt-assembly:0.15.0 (sbtVersion=1.0, scalaVersion=2.12)
[warn]          com.typesafe.sbt:sbt-ghpages:0.6.2 (sbtVersion=1.0, scalaVersion=2.12)
[warn] 
[warn]  Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading com.typesafe:sbt-mima-plugin;sbtVersion=1.0;scalaVersion=2.12:0.6.1
[error]   Not found
[error]   Not found
[error]   not found: /Users/seddonshen/.ivy2/local/com.typesafe/sbt-mima-plugin/scala_2.12/sbt_1.0/0.6.1/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/typesafe/sbt-mima-plugin_2.12_1.0/0.6.1/sbt-mima-plugin-0.6.1.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/maven-releases/com/typesafe/sbt-mima-plugin_2.12_1.0/0.6.1/sbt-mima-plugin-0.6.1.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/maven-snapshots/com/typesafe/sbt-mima-plugin_2.12_1.0/0.6.1/sbt-mima-plugin-0.6.1.pom
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe/sbt-mima-plugin/0.6.1/ivys/ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/ivy-snapshots/com.typesafe/sbt-mima-plugin/0.6.1/ivys/ivy.xml
[error] Error downloading com.eed3si9n:sbt-unidoc;sbtVersion=1.0;scalaVersion=2.12:0.4.1
[error]   Not found
[error]   Not found
[error]   not found: /Users/seddonshen/.ivy2/local/com.eed3si9n/sbt-unidoc/scala_2.12/sbt_1.0/0.4.1/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/eed3si9n/sbt-unidoc_2.12_1.0/0.4.1/sbt-unidoc-0.4.1.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/maven-releases/com/eed3si9n/sbt-unidoc_2.12_1.0/0.4.1/sbt-unidoc-0.4.1.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/maven-snapshots/com/eed3si9n/sbt-unidoc_2.12_1.0/0.4.1/sbt-unidoc-0.4.1.pom
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.eed3si9n/sbt-unidoc/0.4.1/ivys/ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/ivy-snapshots/com.eed3si9n/sbt-unidoc/0.4.1/ivys/ivy.xml
[error] Error downloading com.typesafe.sbt:sbt-site;sbtVersion=1.0;scalaVersion=2.12:1.3.1
[error]   Not found
[error]   Not found
[error]   not found: /Users/seddonshen/.ivy2/local/com.typesafe.sbt/sbt-site/scala_2.12/sbt_1.0/1.3.1/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-site_2.12_1.0/1.3.1/sbt-site-1.3.1.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/maven-releases/com/typesafe/sbt/sbt-site_2.12_1.0/1.3.1/sbt-site-1.3.1.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/maven-snapshots/com/typesafe/sbt/sbt-site_2.12_1.0/1.3.1/sbt-site-1.3.1.pom
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-site/1.3.1/ivys/ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/ivy-snapshots/com.typesafe.sbt/sbt-site/1.3.1/ivys/ivy.xml
[error] Error downloading com.eed3si9n:sbt-buildinfo;sbtVersion=1.0;scalaVersion=2.12:0.10.0
[error]   Not found
[error]   Not found
[error]   not found: /Users/seddonshen/.ivy2/local/com.eed3si9n/sbt-buildinfo/scala_2.12/sbt_1.0/0.10.0/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/eed3si9n/sbt-buildinfo_2.12_1.0/0.10.0/sbt-buildinfo-0.10.0.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/maven-releases/com/eed3si9n/sbt-buildinfo_2.12_1.0/0.10.0/sbt-buildinfo-0.10.0.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/maven-snapshots/com/eed3si9n/sbt-buildinfo_2.12_1.0/0.10.0/sbt-buildinfo-0.10.0.pom
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.eed3si9n/sbt-buildinfo/0.10.0/ivys/ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/ivy-snapshots/com.eed3si9n/sbt-buildinfo/0.10.0/ivys/ivy.xml
[error] Error downloading com.eed3si9n:sbt-assembly;sbtVersion=1.0;scalaVersion=2.12:0.15.0
[error]   Not found
[error]   Not found
[error]   not found: /Users/seddonshen/.ivy2/local/com.eed3si9n/sbt-assembly/scala_2.12/sbt_1.0/0.15.0/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/eed3si9n/sbt-assembly_2.12_1.0/0.15.0/sbt-assembly-0.15.0.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/maven-releases/com/eed3si9n/sbt-assembly_2.12_1.0/0.15.0/sbt-assembly-0.15.0.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/maven-snapshots/com/eed3si9n/sbt-assembly_2.12_1.0/0.15.0/sbt-assembly-0.15.0.pom
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.eed3si9n/sbt-assembly/0.15.0/ivys/ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/ivy-snapshots/com.eed3si9n/sbt-assembly/0.15.0/ivys/ivy.xml
[error] Error downloading com.typesafe.sbt:sbt-ghpages;sbtVersion=1.0;scalaVersion=2.12:0.6.2
[error]   Not found
[error]   Not found
[error]   not found: /Users/seddonshen/.ivy2/local/com.typesafe.sbt/sbt-ghpages/scala_2.12/sbt_1.0/0.6.2/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-ghpages_2.12_1.0/0.6.2/sbt-ghpages-0.6.2.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/maven-releases/com/typesafe/sbt/sbt-ghpages_2.12_1.0/0.6.2/sbt-ghpages-0.6.2.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/maven-snapshots/com/typesafe/sbt/sbt-ghpages_2.12_1.0/0.6.2/sbt-ghpages-0.6.2.pom
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-ghpages/0.6.2/ivys/ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/ivy-snapshots/com.typesafe.sbt/sbt-ghpages/0.6.2/ivys/ivy.xml
[error]         at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:249)
[error]         at lmcoursier.CoursierDependencyResolution.$anonfun$update$35(CoursierDependencyResolution.scala:218)
[error]         at scala.util.Either$LeftProjection.map(Either.scala:573)
[error]         at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:218)
[error]         at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error]         at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:52)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:102)
[error]         at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:69)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:115)
[error]         at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:115)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:96)
[error]         at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
[error]         at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:129)
[error]         at sbt.Classpaths$.$anonfun$updateTask0$5(Defaults.scala:2950)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error]         at sbt.Execute.work(Execute.scala:290)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (update) sbt.librarymanagement.ResolveException: Error downloading com.typesafe:sbt-mima-plugin;sbtVersion=1.0;scalaVersion=2.12:0.6.1
[error]   Not found
[error]   Not found
[error]   not found: /Users/seddonshen/.ivy2/local/com.typesafe/sbt-mima-plugin/scala_2.12/sbt_1.0/0.6.1/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/typesafe/sbt-mima-plugin_2.12_1.0/0.6.1/sbt-mima-plugin-0.6.1.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/maven-releases/com/typesafe/sbt-mima-plugin_2.12_1.0/0.6.1/sbt-mima-plugin-0.6.1.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/maven-snapshots/com/typesafe/sbt-mima-plugin_2.12_1.0/0.6.1/sbt-mima-plugin-0.6.1.pom
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe/sbt-mima-plugin/0.6.1/ivys/ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/ivy-snapshots/com.typesafe/sbt-mima-plugin/0.6.1/ivys/ivy.xml
[error] Error downloading com.eed3si9n:sbt-unidoc;sbtVersion=1.0;scalaVersion=2.12:0.4.1
[error]   Not found
[error]   Not found
[error]   not found: /Users/seddonshen/.ivy2/local/com.eed3si9n/sbt-unidoc/scala_2.12/sbt_1.0/0.4.1/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/eed3si9n/sbt-unidoc_2.12_1.0/0.4.1/sbt-unidoc-0.4.1.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/maven-releases/com/eed3si9n/sbt-unidoc_2.12_1.0/0.4.1/sbt-unidoc-0.4.1.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/maven-snapshots/com/eed3si9n/sbt-unidoc_2.12_1.0/0.4.1/sbt-unidoc-0.4.1.pom
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.eed3si9n/sbt-unidoc/0.4.1/ivys/ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/ivy-snapshots/com.eed3si9n/sbt-unidoc/0.4.1/ivys/ivy.xml
[error] Error downloading com.typesafe.sbt:sbt-site;sbtVersion=1.0;scalaVersion=2.12:1.3.1
[error]   Not found
[error]   Not found
[error]   not found: /Users/seddonshen/.ivy2/local/com.typesafe.sbt/sbt-site/scala_2.12/sbt_1.0/1.3.1/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-site_2.12_1.0/1.3.1/sbt-site-1.3.1.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/maven-releases/com/typesafe/sbt/sbt-site_2.12_1.0/1.3.1/sbt-site-1.3.1.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/maven-snapshots/com/typesafe/sbt/sbt-site_2.12_1.0/1.3.1/sbt-site-1.3.1.pom
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-site/1.3.1/ivys/ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/ivy-snapshots/com.typesafe.sbt/sbt-site/1.3.1/ivys/ivy.xml
[error] Error downloading com.eed3si9n:sbt-buildinfo;sbtVersion=1.0;scalaVersion=2.12:0.10.0
[error]   Not found
[error]   Not found
[error]   not found: /Users/seddonshen/.ivy2/local/com.eed3si9n/sbt-buildinfo/scala_2.12/sbt_1.0/0.10.0/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/eed3si9n/sbt-buildinfo_2.12_1.0/0.10.0/sbt-buildinfo-0.10.0.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/maven-releases/com/eed3si9n/sbt-buildinfo_2.12_1.0/0.10.0/sbt-buildinfo-0.10.0.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/maven-snapshots/com/eed3si9n/sbt-buildinfo_2.12_1.0/0.10.0/sbt-buildinfo-0.10.0.pom
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.eed3si9n/sbt-buildinfo/0.10.0/ivys/ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/ivy-snapshots/com.eed3si9n/sbt-buildinfo/0.10.0/ivys/ivy.xml
[error] Error downloading com.eed3si9n:sbt-assembly;sbtVersion=1.0;scalaVersion=2.12:0.15.0
[error]   Not found
[error]   Not found
[error]   not found: /Users/seddonshen/.ivy2/local/com.eed3si9n/sbt-assembly/scala_2.12/sbt_1.0/0.15.0/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/eed3si9n/sbt-assembly_2.12_1.0/0.15.0/sbt-assembly-0.15.0.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/maven-releases/com/eed3si9n/sbt-assembly_2.12_1.0/0.15.0/sbt-assembly-0.15.0.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/maven-snapshots/com/eed3si9n/sbt-assembly_2.12_1.0/0.15.0/sbt-assembly-0.15.0.pom
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.eed3si9n/sbt-assembly/0.15.0/ivys/ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/ivy-snapshots/com.eed3si9n/sbt-assembly/0.15.0/ivys/ivy.xml
[error] Error downloading com.typesafe.sbt:sbt-ghpages;sbtVersion=1.0;scalaVersion=2.12:0.6.2
[error]   Not found
[error]   Not found
[error]   not found: /Users/seddonshen/.ivy2/local/com.typesafe.sbt/sbt-ghpages/scala_2.12/sbt_1.0/0.6.2/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-ghpages_2.12_1.0/0.6.2/sbt-ghpages-0.6.2.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/maven-releases/com/typesafe/sbt/sbt-ghpages_2.12_1.0/0.6.2/sbt-ghpages-0.6.2.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/maven-snapshots/com/typesafe/sbt/sbt-ghpages_2.12_1.0/0.6.2/sbt-ghpages-0.6.2.pom
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-ghpages/0.6.2/ivys/ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/ivy-snapshots/com.typesafe.sbt/sbt-ghpages/0.6.2/ivys/ivy.xml
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 
```

**Comment by yoyo115956** [comment]
I'm using sbt version 1.10.0, but the rocketchip on the given branch is already limited to version 1.3.13 and it's all working fine in my situation. 
https://constellation.readthedocs.io/en/latest/Introduction/Installation.html#installing-rocketchip. The code details are also referenced as mentioned by the original author here.

``` shell
(base) liyongting@LAPTOP-MRFD2B0N:~/rocket-chip$ sbt --version
sbt version in this project: 1.3.13
sbt script version: 1.10.0
```

``` shell
(base) liyongting@LAPTOP-MRFD2B0N:~/rocket-chip$ sbt "publishLocal"
[info] welcome to sbt 1.3.13 (Private Build Java 1.8.0_402)
[info] loading settings for project rocket-chip-build from plugins.sbt ...
[info] loading project definition from /home/liyongting/rocket-chip/project
[info] loading settings for project rocketchip from build.sbt ...
[info] loading settings for project hardfloat from build.sbt ...
Using addons:
[info] set current project to rocketchip (in build file:/home/liyongting/rocket-chip/)
[info] Wrote /home/liyongting/rocket-chip/target/scala-2.13/rocketchip_2.13-1.6.0.pom
[info] Main Scala API documentation to /home/liyongting/rocket-chip/target/scala-2.13/api...
[warn] /home/liyongting/rocket-chip/src/main/scala/devices/debug/Debug.scala:957:28: Auto-application to `()` is deprecated. Supply the empty argument list `()` explicitly to invoke method unary_~,


......
[info]  published ivy to /home/liyongting/.ivy2/local/edu.berkeley.cs/rocketchip_2.13/1.6.0/ivys/ivy.xml
[success] Total time: 210 s (03:30), completed Jul 2, 2024 4:22:00 PM
```

**Comment by SeddonShen** [comment]
> I'm using sbt version 1.10.0, but the rocketchip on the given branch is already limited to version 1.3.13 and it's all working fine in my situation. https://constellation.readthedocs.io/en/latest/Introduction/Installation.html#installing-rocketchip. The code details are also referenced as mentioned by the original author here.
> 
> ```shell
> (base) liyongting@LAPTOP-MRFD2B0N:~/rocket-chip$ sbt --version
> sbt version in this project: 1.3.13
> sbt script version: 1.10.0
> ```
> 
> ```shell
> (base) liyongting@LAPTOP-MRFD2B0N:~/rocket-chip$ sbt "publishLocal"
> [info] welcome to sbt 1.3.13 (Private Build Java 1.8.0_402)
> [info] loading settings for project rocket-chip-build from plugins.sbt ...
> [info] loading project definition from /home/liyongting/rocket-chip/project
> [info] loading settings for project rocketchip from build.sbt ...
> [info] loading settings for project hardfloat from build.sbt ...
> Using addons:
> [info] set current project to rocketchip (in build file:/home/liyongting/rocket-chip/)
> [info] Wrote /home/liyongting/rocket-chip/target/scala-2.13/rocketchip_2.13-1.6.0.pom
> [info] Main Scala API documentation to /home/liyongting/rocket-chip/target/scala-2.13/api...
> [warn] /home/liyongting/rocket-chip/src/main/scala/devices/debug/Debug.scala:957:28: Auto-application to `()` is deprecated. Supply the empty argument list `()` explicitly to invoke method unary_~,
> 
> 
> ......
> [info]  published ivy to /home/liyongting/.ivy2/local/edu.berkeley.cs/rocketchip_2.13/1.6.0/ivys/ivy.xml
> [success] Total time: 210 s (03:30), completed Jul 2, 2024 4:22:00 PM
> ```

OK, I will try again , thx!!
