### ISSUE TITLE
Error building BOOM under CONFIG=MediumBoomConfig

### ISSUE THREAD

**Issue by mbrandalero** [riscv-boom/riscv-boom#81]
**a require() statement fails in icache.scala within the boom.ifu.ICacheModule (icache.scala:131).**

Full error message:

```
[mbrandalero: verisim]$ make CONFIG=MediumBoomConfig 
mkdir -p /home/mbrandalero/tools/boom-template/verisim/generated-src 
cd /home/mbrandalero/tools/boom-template && java -Xmx2G -Xss8M -jar /home/mbrandalero/tools/boom-template/rocket-chip/sbt-launch.jar "runMain boom.system.Generator  /home/mbrand
alero/tools/boom-template/verisim/generated-src boom.system TestHarness boom.system MediumBoomConfig" 
[info] Loading project definition from /home/mbrandalero/tools/boom-template/project 
[info] Loading settings from build.sbt ... 
[info] Set current project to boom-template (in build file:/home/mbrandalero/tools/boom-template/) 
[info] Running boom.system.Generator /home/mbrandalero/tools/boom-template/verisim/generated-src boom.system TestHarness boom.system MediumBoomConfig 
[info] [0.003] Elaborating design... 


Building TestHarness for an ExampleBoomSystem. 

Interrupt map (2 harts 2 interrupts): 
 [1, 2] => dut 

[error] (run-main-0) java.lang.reflect.InvocationTargetException 
[error] java.lang.reflect.InvocationTargetException 
[error]         at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) 
[error]         at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) 
[error]         at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) 
[error]         at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
[error]         at freechips.rocketchip.util.HasGeneratorUtilities$$anonfun$2.apply(GeneratorUtils.scala:51) 
[error]         at freechips.rocketchip.util.HasGeneratorUtilities$$anonfun$2.apply(GeneratorUtils.scala:48) 
[error]         at chisel3.core.Module$.do_apply(Module.scala:49) 
[error]         at chisel3.Driver$$anonfun$elaborate$1.apply(Driver.scala:93) 
[error]         at chisel3.Driver$$anonfun$elaborate$1.apply(Driver.scala:93) 
[error]         at chisel3.internal.Builder$$anonfun$build$1.apply(Builder.scala:297) 
[error]         at chisel3.internal.Builder$$anonfun$build$1.apply(Builder.scala:295) 
[error]         at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58) 
[error]         at chisel3.internal.Builder$.build(Builder.scala:295) 
[error]         at chisel3.Driver$.elaborate(Driver.scala:93) 
[error]         at freechips.rocketchip.util.HasGeneratorUtilities$class.elaborate(GeneratorUtils.scala:54) 
[error]         at boom.system.Generator$.elaborate(Generator.scala:13) 
[error]         at freechips.rocketchip.util.GeneratorApp$class.circuit(GeneratorUtils.scala:91) 
[error]         at boom.system.Generator$.circuit$lzycompute(Generator.scala:13) 
[error]         at boom.system.Generator$.circuit(Generator.scala:13) 
[error]         at freechips.rocketchip.util.GeneratorApp$class.generateFirrtl(GeneratorUtils.scala:97) 
[error]         at boom.system.Generator$.generateFirrtl(Generator.scala:13) 
[error]         at boom.system.Generator$.delayedEndpoint$boom$system$Generator$1(Generator.scala:95) 
[error]         at boom.system.Generator$delayedInit$body.apply(Generator.scala:13) 
[error]         at scala.Function0$class.apply$mcV$sp(Function0.scala:34) 
[error]         at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12) 
[error]         at scala.App$$anonfun$main$1.apply(App.scala:76) 
[error]         at scala.App$$anonfun$main$1.apply(App.scala:76) 
[error]         at scala.collection.immutable.List.foreach(List.scala:381) 
[error]         at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35) 
[error]         at scala.App$class.main(App.scala:76) 
[error]         at boom.system.Generator$.main(Generator.scala:13) 
[error]         at boom.system.Generator.main(Generator.scala) 
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
[error]         at java.lang.reflect.Method.invoke(Method.java:498) 
[error]         at sbt.Run.invokeMain(Run.scala:93) 
[error]         at sbt.Run.run0(Run.scala:87) 
[error]         at sbt.Run.execute$1(Run.scala:65) 
[error]         at sbt.Run.$anonfun$run$4(Run.scala:77) 
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12) 
[error]         at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10) 
[error]         at sbt.TrapExit$App.run(TrapExit.scala:252) 
[error]         at java.lang.Thread.run(Thread.java:748) 
**[error] Caused by: java.lang.IllegalArgumentException: requirement failed 
[error]         at scala.Predef$.require(Predef.scala:207) 
[error]         at boom.ifu.ICacheModule.<init>(icache.scala:131)** 
[error]         at boom.ifu.ICache.module$lzycompute(icache.scala:46) 
[error]         at boom.ifu.ICache.module(icache.scala:45) 
[error]         at boom.ifu.ICache.module(icache.scala:39) 
[error]         at freechips.rocketchip.diplomacy.LazyModuleImpLike$$anonfun$4$$anonfun$5.apply(LazyModule.scala:156) 
[error]         at freechips.rocketchip.diplomacy.LazyModuleImpLike$$anonfun$4$$anonfun$5.apply(LazyModule.scala:156) 
[error]         at chisel3.core.Module$.do_apply(Module.scala:49) 
[error]         at freechips.rocketchip.diplomacy.LazyModuleImpLike$$anonfun$4.apply(LazyModule.scala:156) 
[error]         at freechips.rocketchip.diplomacy.LazyModuleImpLike$$anonfun$4.apply(LazyModule.scala:154) 
[error]         at scala.collection.immutable.List.flatMap(List.scala:327) 
[error]         at freechips.rocketchip.diplomacy.LazyModuleImpLike$class.instantiate(LazyModule.scala:154) 
[error]         at freechips.rocketchip.diplomacy.LazyModuleImp.instantiate(LazyModule.scala:183) 
[error]         at freechips.rocketchip.diplomacy.LazyModuleImp.<init>(LazyModule.scala:184) 
[error]         at boom.ifu.BoomFrontendModule.<init>(frontend.scala:153) 
[error]         at boom.ifu.BoomFrontend.module$lzycompute(frontend.scala:140) 
[error]         at boom.ifu.BoomFrontend.module(frontend.scala:140) 
[error]         at boom.ifu.BoomFrontend.module(frontend.scala:139) 
[error]         at freechips.rocketchip.diplomacy.LazyModuleImpLike$$anonfun$4$$anonfun$5.apply(LazyModule.scala:156) 
[error]         at freechips.rocketchip.diplomacy.LazyModuleImpLike$$anonfun$4$$anonfun$5.apply(LazyModule.scala:156) 
[error]         at chisel3.core.Module$.do_apply(Module.scala:49) 
[error]         at freechips.rocketchip.diplomacy.LazyModuleImpLike$$anonfun$4.apply(LazyModule.scala:156) 
[error]         at freechips.rocketchip.diplomacy.LazyModuleImpLike$$anonfun$4.apply(LazyModule.scala:154) 
[error]         at scala.collection.immutable.List.flatMap(List.scala:327) 
[error]         at freechips.rocketchip.diplomacy.LazyModuleImpLike$class.instantiate(LazyModule.scala:154) 
[error]         at freechips.rocketchip.diplomacy.LazyModuleImp.instantiate(LazyModule.scala:183) 
[error]         at freechips.rocketchip.diplomacy.LazyModuleImp.<init>(LazyModule.scala:184) 
[error]         at freechips.rocketchip.tile.BaseTileModuleImp.<init>(BaseTile.scala:173) 
[error]         at boom.common.BoomTileModuleImp.<init>(tile.scala:102) 
[error]         at boom.common.BoomTile.module$lzycompute(tile.scala:99) 
[error]         at boom.common.BoomTile.module(tile.scala:99) 
[error]         at boom.common.BoomTile.module(tile.scala:38) 
[error]         at freechips.rocketchip.diplomacy.LazyModuleImpLike$$anonfun$4$$anonfun$5.apply(LazyModule.scala:156) 
[error]         at freechips.rocketchip.diplomacy.LazyModuleImpLike$$anonfun$4$$anonfun$5.apply(LazyModule.scala:156) 
[error]         at chisel3.core.Module$.do_apply(Module.scala:49) 
[error]         at freechips.rocketchip.diplomacy.LazyModuleImpLike$$anonfun$4.apply(LazyModule.scala:156) 
[error]         at freechips.rocketchip.diplomacy.LazyModuleImpLike$$anonfun$4.apply(LazyModule.scala:154) 
[error]         at scala.collection.immutable.List.flatMap(List.scala:327) 
[error]         at freechips.rocketchip.diplomacy.LazyModuleImpLike$class.instantiate(LazyModule.scala:154) 
[error]         at freechips.rocketchip.diplomacy.LazyModuleImp.instantiate(LazyModule.scala:183) 
[error]         at freechips.rocketchip.diplomacy.LazyModuleImp.<init>(LazyModule.scala:184) 
[error]         at freechips.rocketchip.subsystem.BareSubsystemModuleImp.<init>(BaseSubsystem.scala:19) 
[error]         at freechips.rocketchip.subsystem.BaseSubsystemModuleImp.<init>(BaseSubsystem.scala:101) 
[error]         at boom.system.BoomSubsystemModule.<init>(BoomSubsystem.scala:145) 
[error]         at boom.system.ExampleBoomSystemModule.<init>(ExampleBoomSystem.scala:22) 
[error]         at boom.system.ExampleBoomSystem.module$lzycompute(ExampleBoomSystem.scala:19) 
[error]         at boom.system.ExampleBoomSystem.module(ExampleBoomSystem.scala:19) 
[error]         at boom.system.TestHarness$$anonfun$1.apply(TestHarness.scala:15) 
[error]         at boom.system.TestHarness$$anonfun$1.apply(TestHarness.scala:15) 
[error]         at chisel3.core.Module$.do_apply(Module.scala:49) 
[error]         at boom.system.TestHarness.<init>(TestHarness.scala:15) 
[error]         at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) 
[error]         at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) 
[error]         at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) 
[error]         at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
[error]         at freechips.rocketchip.util.HasGeneratorUtilities$$anonfun$2.apply(GeneratorUtils.scala:51) 
[error]         at freechips.rocketchip.util.HasGeneratorUtilities$$anonfun$2.apply(GeneratorUtils.scala:48) 
[error]         at chisel3.core.Module$.do_apply(Module.scala:49) 
[error]         at chisel3.Driver$$anonfun$elaborate$1.apply(Driver.scala:93) 
[error]         at chisel3.Driver$$anonfun$elaborate$1.apply(Driver.scala:93) 
[error]         at chisel3.internal.Builder$$anonfun$build$1.apply(Builder.scala:297) 
[error]         at chisel3.internal.Builder$$anonfun$build$1.apply(Builder.scala:295) 
[error]         at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58) 
[error]         at chisel3.internal.Builder$.build(Builder.scala:295) 
[error]         at chisel3.Driver$.elaborate(Driver.scala:93) 
[error]         at freechips.rocketchip.util.HasGeneratorUtilities$class.elaborate(GeneratorUtils.scala:54) 
[error]         at boom.system.Generator$.elaborate(Generator.scala:13) 
[error]         at freechips.rocketchip.util.GeneratorApp$class.circuit(GeneratorUtils.scala:91) 
[error]         at boom.system.Generator$.circuit$lzycompute(Generator.scala:13) 
[error]         at boom.system.Generator$.circuit(Generator.scala:13) 
[error]         at freechips.rocketchip.util.GeneratorApp$class.generateFirrtl(GeneratorUtils.scala:97) 
[error]         at boom.system.Generator$.generateFirrtl(Generator.scala:13) 
[error]         at boom.system.Generator$.delayedEndpoint$boom$system$Generator$1(Generator.scala:95) 
[error]         at boom.system.Generator$delayedInit$body.apply(Generator.scala:13) 
[error]         at scala.Function0$class.apply$mcV$sp(Function0.scala:34) 
[error]         at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12) 
[error]         at scala.App$$anonfun$main$1.apply(App.scala:76) 
[error]         at scala.App$$anonfun$main$1.apply(App.scala:76) 
[error]         at scala.collection.immutable.List.foreach(List.scala:381) 
[error]         at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35) 
[error]         at scala.App$class.main(App.scala:76) 
[error]         at boom.system.Generator$.main(Generator.scala:13) 
[error]         at boom.system.Generator.main(Generator.scala) 
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
[error]         at java.lang.reflect.Method.invoke(Method.java:498) 
[error]         at sbt.Run.invokeMain(Run.scala:93) 
[error]         at sbt.Run.run0(Run.scala:87) 
[error]         at sbt.Run.execute$1(Run.scala:65) 
[error]         at sbt.Run.$anonfun$run$4(Run.scala:77) 
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12) 
[error]         at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10) 
[error]         at sbt.TrapExit$App.run(TrapExit.scala:252) 
[error]         at java.lang.Thread.run(Thread.java:748) 
[error] java.lang.RuntimeException: Nonzero exit code: 1 
[error]         at sbt.Run$.executeTrapExit(Run.scala:124) 
[error]         at sbt.Run.run(Run.scala:77) 
[error]         at sbt.Defaults$.$anonfun$bgRunMainTask$6(Defaults.scala:1147) 
[error]         at sbt.Defaults$.$anonfun$bgRunMainTask$6$adapted(Defaults.scala:1142) 
[error]         at sbt.internal.BackgroundThreadPool.$anonfun$run$1(DefaultBackgroundJobService.scala:366) 
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12) 
[error]         at scala.util.Try$.apply(Try.scala:209) 
[error]         at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:289) 
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 
[error]         at java.lang.Thread.run(Thread.java:748) 
[error] (Compile / runMain) Nonzero exit code: 1 
[error] Total time: 10 s, completed May 17, 2018 4:34:35 PM 
make: *** [/home/mbrandalero/tools/boom-template/Makefrag:30: /home/mbrandalero/tools/boom-template/verisim/generated-src/boom.system.TestHarness.MediumBoomConfig.fir] Error 1
```

**Comment by ccelio** [comment]
This is likely a missing line in which the system bus width needs to be modified:
https://github.com/ucb-bar/riscv-boom/blob/master/src/main/scala/common/configs.scala#L84

There is a non-obvious coupling between fetchWidth and systemBusWidth that must be maintained.

**Comment by ccelio** [comment]
Thanks for the report. It's been fixed.
